FROM ubuntu:latest

COPY script.sh /usr/local/bin/script.sh

RUN chmod +x /usr/local/bin/script.sh

RUN /usr/local/bin/script.sh

RUN echo "Inicio de Script" && \
    echo "Ejecutando Tarea 1" && \
    echo "Ejecutando Tarea 2" && \
    echo "Script Finalizado."